### ISSUE TITLE
DPS is meaningless

### ISSUE THREAD

**Issue by Trouvist** [wchill/steamSummerMinigame#165] opened 2015-06-15 21:20 UTC
Beyond somewhere to spend excess money when it's prohibitively expensive, the only upgrade that really matters is Boss Loot.

1) Cripple Spawners destroys them to 1 HP
2) Cripple Monster destroys them to 1 HP
3) Cripple Monster brings ANY boss to 5%, and at 1000 players with nuke, that averages out to one nuke going online every 4 seconds (to finish the boss) (that's just for tactical nukes, ignore napalm and cluster)
4) Raining gold pays for the upgrades while bosses wait for that nuke to come online
5) Boss loot gives crits, too, which helps out people who are less than 100%

A) This removes the need for Anything other than Boos loot (as primary spender), lucky shot (as secondary spending), and then regular guns (when everything else is prohibitively expensive)
B) Can we program the script to just autobuy boss loot, then lucky shot, then the click weapons (in smart order, always doing the cheapest/damage cost one?)  And never spend more on a gun than boss loot or lucky shot (150% stakcing is better than any +flat rate could be)

Why would we need much else?  The DPS relative to overall health is meaningless; therefore (and obviously) abilities are the only things doing anything.

**Comment by corymcdonough** [comment] 2015-06-15 21:26
Which means we need to prioritize ability distribution to prevent overlapping usage.

**Comment by Chdata** [comment] 2015-06-15 21:31
Auto DPS is useless because it's additive.

At some point, boss HP becomes so much that additional X tier DPC upgrades is virtually meaningless and it becomes a game of using abilities that damage by 20%, 50%, 95%, etc.

**Comment by corymcdonough** [comment] 2015-06-15 21:35
Also, until non-boss enemy health outgrows our DPS significantly, it would actually be better NOT to speclialize in an element. **We don't have time to properly switch lanes to take advantage of elemental weaknesses. Then on bosses, we only have a 1/4 chance of hitting our elemental weakness.**

If Valve keeps providing us with another tier of upgrades each day, it might be more advantageous NOT to specialize. But this is coming from someone who hasn't seen level 25k, where things might slow down. Ultimately, I do think the long game is more important. If sacrificing some DPS in lower levels due to elemental specialization means we can DPS multiple mobs faster once we hit higher levels, it would be worth it.

**Comment by Trouvist** [comment] 2015-06-15 21:41
I alluded to this in https://github.com/wchill/steamSummerMinigame/issues/90 for ability distribution, maybe we could do steam-id % 9, and everyone can go on boss levels?

**Comment by Chdata** [comment] 2015-06-15 21:41
What about Element Max?

It uses whatever your max element is, regardless of the current lane's weakness.

I was told the script does actually use them, so I assume it uses them enough to keep one active in every lane at all times.

In which case, splitting between two elements will cut your bonus in half.

**Comment by Trouvist** [comment] 2015-06-15 21:42
Cory, and chdata, if people decide to get above 50% crit, and crits dont stack with elemental damage, then we can ignore elementals entirely because its diminishing returns as crits go up

**Comment by Chdata** [comment] 2015-06-15 21:46
I thought everyone already was getting 100% crits (as in, like 85 at the start + drops)

**Comment by Trouvist** [comment] 2015-06-15 21:50
chdata, I mean that if you have 100% crit rate, your elemental damage is never taken into account (so putting points into elemental affitinity is pointless)

**Comment by corymcdonough** [comment] 2015-06-15 21:51
Not all of us were able to get into high-numbered rooms in previous days. We shouldn't assume everyone has max crit, but at the very least an auto-upgrade script should realize the possibility of max crit.

**Comment by Chdata** [comment] 2015-06-15 21:52
Ah then you're right, since over time you'll get closer to 100% crit if you aren't, and once you're there the elemental damage will be null, may as well max on crits.

**Comment by Trouvist** [comment] 2015-06-15 22:03
All of your points are valid, but take them to the logical conclusions: DPS is meaningless.  Boss items matter the most, and you get them fastest by killing more bosses.  So max Boss Loot, secondarily max DPS (because you do have to hit for 1 at some point) and rapid fire through the levels, to the point of even skipping rain, because rain was supposed to be for actually getting higher DPS but we're way past that now.

**Comment by corymcdonough** [comment] 2015-06-15 22:07
I still don't think DPS is meaningless. If you drop all the DPS then the Spawner waves will require items to defeat.

**Comment by Chdata** [comment] 2015-06-15 22:18
DPS isn't meaningless until X wave where the bosses have enough hp for it to be meaningless. Until then, it lets us burn through waves almost instantly even without abilities.

**Comment by Trouvist** [comment] 2015-06-15 22:18
if 1000 people have 1% higher boss drops, thats 10 chances for us to get a "cripple spawner", "cripple monster" drop, etc.... except people have 40% boss loot drop chances, so that means that 400 new drops happen each boss death,. almsot guaranteeing we have FAR MORE THAN ENOUGH cripple and throw money upgrades than necessary to kill the next 10 levels

**Comment by Chdata** [comment] 2015-06-15 22:19
imo our biggest obstacle is the transition between levels / changing lanes time.

**Comment by corymcdonough** [comment] 2015-06-15 22:21
Do we know whether 15 spammed cluster bombs in one lane apply to the same 4 mobs or will it drop some on the next spawns?

**Comment by Trouvist** [comment] 2015-06-15 22:27
cory, you get the ability back if the server fails to use it, so if you're stockpilig them, it means there are enough other people trying it that you're effectively saving yours for later, its why we have such perfect killing records per nonboss levels

**Comment by corymcdonough** [comment] 2015-06-15 22:33
Okay, then that makes a lot more sense to me. However, does Cripple Spawner fail to be used if the mob is at 1hp already? And what about Napalm, where you could just as easily have multiple used at once? I just saw literally 90 of them used at once in a lane.

**Comment by Trouvist** [comment] 2015-06-15 22:34
I have no idea, but i think napalm is misused, same with cluster and nuke (hence my earlier post about stratification of abilities based on modulus of steam id and level number)

**Comment by Trouvist** [comment] 2015-06-15 22:37
Something along the lines of:

if (level % 10 == hashCode(w.g_steamID) % 9 + 1 || level % 10 == 0)

**Comment by EricWR** [comment] 2015-06-15 22:46
According to wchill, element still applies even at 100% crit. It just isn't included in the crit number the server sends you. He said he tested that on the first day somehow.

**Comment by Trouvist** [comment] 2015-06-15 22:46
Then I stand correct, but it still doesnt account for the fact that DPS is meaningless, lol :)

**Comment by wchill** [comment] 2015-06-16 00:44
@EricWR I don't remember saying that, but anyway the case is that it doesn't apply. I didn't have 100% crit at the time.

**Comment by EricWR** [comment] 2015-06-16 00:47
@wchill It was a couple days ago when TRT and I were asking about it. Well that's good to know element doesn't work. I'll stop spreading misinformation.

**Comment by corymcdonough** [comment] 2015-06-16 00:54
I can confirm that Cripple Spawner can be freely spammed. I saw mine refund about a dozen times before it finally went through.

**Comment by corymcdonough** [comment] 2015-06-16 02:51
Room 4 just used 499 Decrease Cooldowns at the same time.

**Comment by StaplerGuy** [comment] 2015-06-16 04:08
Do we have actual proof of the crit/element not stacking thing? Doesn't that mean the script should just plain ignore the elemental damage upgrades altogether?

**Comment by brendanvos** [comment] 2015-06-16 05:44
It's really hard to "prove" anything related to the actual effects certain abilities are having. We don't know what limitations occur on the server side.

@corymcdonough What do you mean by "That's enough to keep it online constantly"? I don't understand this concept.

**Comment by oedw** [comment] 2015-06-16 06:48
@brendanvos I think @corymcdonough is saying that instead of the decrease cooldown being spammed, it could've been used one after another (as soon as the previous one expired) pretty much until the game ends

**Comment by wchill** [comment] 2015-06-16 09:01
I'm going to close this discussion, as some measures have been taken to reduce waste of abilities in https://github.com/wchill/steamSummerMinigame/commit/32685d2b243b8ece23d0a0e33973559704bc6522.

**Closed by wchill** 2015-06-16 09:01 UTC
