### ISSUE TITLE
If cooldown is available us cooldown before using nuke / nepalm / cluster bomb

### ISSUE THREAD

**Issue by KoetseJ** [wchill/steamSummerMinigame#122] opened 2015-06-14 21:15 UTC
It looks like it currently doesn't use the cooldown ability, it would be nice if it used cooldown(if its available) before using nuke / napalm / cluster bomb.

**Comment by wchill** [comment] 2015-06-14 21:30
Duplicate of #82

**Closed by wchill** 2015-06-14 21:30 UTC
