### ISSUE TITLE
Upgrade elementary damage - buttons missing in browser (FF)

### ISSUE THREAD

**Issue by Siedlerchr** [wchill/steamSummerMinigame#152] opened 2015-06-15 16:47 UTC
Hi, 
after the start of the new game after the global steam reset, the upgrade buttons on elementary damge 
![elementary](https://cloud.githubusercontent.com/assets/320228/8165214/e0a0dde0-138e-11e5-9c58-c8c33f1c56db.png)

Not sure, if this is script related, anyone else having same problem?

**Comment by StaplerGuy** [comment] 2015-06-15 16:48
That's a deliberate feature, designed to get you to target the correct elemental upgrade.

**Comment by oedw** [comment] 2015-06-15 17:30
Uncheck "Lock element upgrades"
![capture](https://cloud.githubusercontent.com/assets/4912057/8165959/77a79148-1349-11e5-85b9-cc190e1418db.PNG)

**Comment by ZeekDaGeek** [comment] 2015-06-15 18:45
Essentially the script reads your Steam user ID, based off of that number it assigns you an element. In theory 1/4th of the people using the script are assigned each element to balance out the overall DPS. Focus on the Element you're assigned and other users will pick up the slack in other lanes.

**Comment by Siedlerchr** [comment] 2015-06-15 18:52
Thanks a lot for the answers. I will keep up updating the designated element and hope the others use the script as well.

**Comment by Trouvist** [comment] 2015-06-16 02:51
Working as intended, closing this.  Based on the distributions of the different elements, people are using it properly.

**Closed by Trouvist** 2015-06-16 02:51 UTC
