### ISSUE TITLE
Slave vs. higher request rate

### ISSUE THREAD

**Issue by subnet-** [wchill/steamSummerMinigame#81] opened 2015-06-14 11:01 UTC
People have reported that having multiple windows open have a better effect on Goldrain.
Can't we instead increase the POST-request rate?

Source: http://www.reddit.com/r/SteamMonsterGame/comments/39s6z4/slave_script_increase_autoclicker_cps_and_gold/
https://github.com/ags131/steamMinigameSlaveScript

**Comment by wchill** [comment] 2015-06-14 15:19
I have not been able to verify that this is working despite my best efforts.

**Comment by ags131** [comment] 2015-06-16 01:04
The day I posted it it was confirmed working, since then I haven't been able to determine if its working. (I've also been in Reddit #2, so kinda hard to tell if anything helps at all)

**Comment by wchill** [comment] 2015-06-16 06:36
I'm going to close this as it's not worth implementing a feature that is currently not confirmed working and will likely be patched soon anyway.

**Closed by wchill** 2015-06-16 06:36 UTC
Labels: Help wanted, Question
